---
title: "Software Installation"
editor: "source"
---

## 1. What software do we need to join the lecture?

-   Latest version of R

-   Latest version of RStudio

-   For Windows users only: Latest version of Rtools

## 2. From where should we download the software?

### 2.1 Link to download R software: <https://cran.rstudio.com/>

To install R on **Windows**, click the “Download R for Windows” link. Then click the “base” link. Next, click “Download R-4.6.0 for Windows". The downloading will start.

To install R on a **Mac**, click the “Download R for Mac” link. Next, click on the `R-4.6.0-arm64.pkg`.

### 2.2 Link to download R Studio software: <https://posit.co/download/rstudio-desktop>

Just click the “Download RStudio for XXXX” button, where XXXX is your operating system.

### 2.3 Link to download RTools: <https://cran.r-project.org/bin/windows/Rtools/>

Find and download the version compatible with your installed version of R. For example, if you have R version 4.5.3, you need to install the corresponding Rtools version that matches it. That is "R Tools 4.5. " If there is no compatible Rtools version available for your R version, then download the latest available Rtools release.

Find and download the version compatible with your installed version of R.

## 3. How to install software?

First, install R. Run the installer and complete the setup step by step.

After completing the installation of R, next install RStudio. Install it like a normal application.

After that, install Rtools (Windows users only) by using the version that is compatible with your installed version of R. Complete the installation process.

**Note:** Do not install them in parallel. Install R first, then RStudio, and finally Rtools.

## 4. How can we verify whether all three software (R, RStudio, and Rtools) have been installed correctly?

You can check whether everything is installed properly in a simple way after setup.

First, open RStudio. If it opens without errors, R is already correctly installed (because RStudio runs on top of R).

Then in the RStudio Console, type the following command and press enter.

``` r
R.version.string
```

If it shows a version number like R 4.x.x, then R is correctly installed.

For Rtools (Windows only), run the following command as well

``` r
Sys.which("make")
```

You should be able to see a message like `"C:\\rtools45\\usr\\bin\\make.exe"`.

If it returns a path (not empty), Rtools is correctly configured.

## 5. Optional step only for windows users

Type the following

``` r
install.packages("pkgbuild")
pkgbuild::has_build_tools(debug = TRUE)
```

If it returns TRUE, everything (R + Rtools) is set up properly for package installation.

## 6. Additional resourcs

Video illustrations

[Installing R](youtube.com/watch?v=aRwxsAEoRzs&pp=0gcJCQYLAYcqIYzv)

[Installing R Studio](https://www.youtube.com/watch?v=Q1NRj2Dzdn0)
